# @name signin
POST http://localhost:8190/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}

@token = {{signin.response.body.token}}

### get chat list

GET http://localhost:8190/api/chat
Authorization: Bearer {{token}}