# ### signup user
# POST http://localhost:8190/api/signup
# Content-Type: application/json

# {
#     "workspace": "acme",
#     "fullname": "Tyr Chen",
#     "email": "tchen@acme.org",
#     "password": "123456"
# }


# @name signin
POST http://localhost:8190/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

@token = {{signin.response.body.token}}

### get chat list

GET http://localhost:8190/api/chats
Authorization: Bearer {{token}}


### create chat
POST http://localhost:8190/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Tyr Chen",
    "members": [2, 0],
    "public": false
}